name: build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:unstable

    steps:
    - name: get git
      run: |
        apt-get update
        apt-get install -y git
        
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        submodules: recursive
        
    - name: get d++ and dependencies
      run: |
        apt-get install -y \
          g++-16 \
          gcc-16 \
          build-essential \
          pkg-config \
          cmake \
          wget \
          libsqlite3-dev \
          libmagick++-7.q16hdri-dev \
          nlohmann-json3-dev \
          libsodium-dev \
          libssl-dev \
          zlib1g-dev \
          ocl-icd-opencl-dev \
          opencl-headers \
          libopus0 \
          libopus-dev

        wget -O dpp.deb https://github.com/brainboxdotcc/DPP/releases/download/v10.1.4/libdpp-10.1.4-linux-x64.deb
        dpkg -i dpp.deb || apt-get install -f -y

    - name: Build D+++++++
      run: |
        git clone https://github.com/joshuazcchen/dpp_enhanced_roles.git
        cmake -S dpp_enhanced_roles -B dpp_enhanced_roles/build -DCMAKE_BUILD_TYPE=Release
        cmake --build dpp_enhanced_roles/build --parallel $(nproc)
        cmake --install dpp_enhanced_roles/build

    - name: Configure CMake
      env:
        CC: gcc-16
        CXX: g++-16
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Unit tests
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
