name: License Header Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-headers:
    name: verify headers
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: scan files
      run: |
        error_found=0
        
        files=$(find . -type f \( -name "*.cpp" -o -name "*.h" \) ! -path "*/build/*")
        
        for file in $files; do
          if ! head -n 5 "$file" | grep -q "PolyForm Noncommercial License"; then
            echo "::error file=$file,line=1::missing header"
            error_found=1
          fi
        done
        
        if [ "$error_found" -ne 0 ]; then
          echo "missing header in one or more files"
          exit 1
        fi
        
        echo "all files tagged"
